# Gemini API Key
GEMINI_API_KEY = "AIzaSyD1Ozl5If-8QAQdSdjAwV0PLuYPn9PUvIg"

# Email credentials
SENDER_EMAIL = "shlokkumar4606@gmail.com"
EMAIL_PASSWORD = "dyuw tbtt ybfj olpc"  # ✅ Changed this line

# SMTP settings
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
